# Generated by Django 4.1 on 2022-08-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='player', max_length=100),
        ),
    ]
