# Generated by Django 4.1 on 2022-08-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='first name', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='last name', max_length=100),
        ),
    ]
